var text=document.getElementById('text1')
var text2=document.getElementById('text2')
var text3=document.getElementById('text3')
var con=document.getElementById('con')

setTimeout(()=>{
    setTimeout(()=>{
        setTimeout(()=>{
            setTimeout(()=>{
                setTimeout(()=>{
                    setTimeout(()=>{
                        setTimeout(()=>{
                            setTimeout(()=>{
                                setTimeout(()=>{
                                    setTimeout(()=>{
                                        setTimeout(()=>{
                                            text.innerText=`HAPPY`;
                                            text.style.color='orange';
                                            text2.innerText=`INDEPENDANCE`;
                                            text2.style.color='white'
                                            text3.innerText=`DAY`;
                                            text3.style.color='green';
                                            con.style.background='transparent';
                                            con.style.borderColor='black';
                                            document.body.style.background='black'
                                            },1000);
                                    con.style.borderColor='green';
                                    text.style.color='green';
                                    text.innerText=`1`},950);
                                con.style.borderColor='white';
                                text.style.color='blue';
                                text.innerText=`2`},900);
                            document.body.style.background='black'
                            con.style.borderColor='orange'; 
                            text.style.color='orange';
                            text.innerText=`3`},850);
                        text.style.color='white';
                        text.innerText=`4`},800);
                    text.style.color='white';
                    text.innerText=`5`},750);
                text.style.color='white';
                text.innerText=`6`},700);
            text.style.color='white';
            text.innerText=`7`},650);
        text.style.color='white';
        text.innerText=`8`},600);
    text.style.color='white';
    text.innerText=`9`},550);
text.style.color='white';
text.innerText=`10`},500);
