var text=document.getElementById('text1')
var text2=document.getElementById('text2')
var text3=document.getElementById('text3')
var con=document.getElementById('con')

setTimeout(()=>{
    setTimeout(()=>{
        setTimeout(()=>{
            setTimeout(()=>{
                setTimeout(()=>{
                    setTimeout(()=>{
                        setTimeout(()=>{
                            setTimeout(()=>{
                                setTimeout(()=>{
                                    setTimeout(()=>{
                                        setTimeout(()=>{
                                            text.innerText=`HAPPY`;
                                            text.style.color='orange';
                                            text2.innerText=`INDEPENDANCE`;
                                            text2.style.color='white'
                                            text3.innerText=`DAY`;
                                            text3.style.color='green';
                                            con.style.background='transparent';
                                            con.style.borderColor='black';
                                            document.body.style.background='black'
                                            },1000);
                                    con.style.borderColor='green';
                                    text.style.color='green';
                                    text.innerText=`1`},1900);
                                con.style.borderColor='white';
                                document.body.style.background='black'
                                text.style.color='blue';
                                text.innerText=`2`},1800);
                            con.style.borderColor='orange'; 
                            text.style.color='orange';
                            text.innerText=`3`},1700);
                        text.style.color='white';
                        text.innerText=`4`},1600);
                    text.style.color='white';
                    text.innerText=`5`},1500);
                text.style.color='white';
                text.innerText=`6`},1400);
            text.style.color='white';
            text.innerText=`7`},1300);
        text.style.color='white';
        text.innerText=`8`},1200);
    text.style.color='white';
    text.innerText=`9`},1100);
text.style.color='white';
text.innerText=`10`},1000);
